#!/usr/bin/env bash
sudo apt update
sudo apt install -y nginx

# Define the custom Nginx response header
custom_header="add_header X-Served-By \$hostname;"

# Add the custom header to the Nginx configuration
sudo sed -i "s/# server_tokens off;/# server_tokens off;\n\t$custom_header/" /etc/nginx/nginx.conf

# Restart Nginx to apply the changes
sudo systemctl restart nginx
